export class States {
    list = {
    Brazil : [
       /* 'Acre (AC)',
        'Alagoas (AL)',
        'Amapá (AP)',
        'Amazonas (AM)',
        'Bahia (BA)',
        'Ceará (CE)',
        'Distrito Federal (DF)',
        'Espírito Santo (ES)',
        'Goiás (GO)',
        'Maranhão (MA)',
        'Mato Grosso (MT)',
        'Mato Grosso do Sul (MS)',
        'Minas Gerais (MG)',
        'Pará (PA)',
        'Paraíba (PB)',*/
        'Paraná (PR)',
        /*'Pernambuco (PE)',
        'Piauí (PI)',
        'Rio de Janeiro (RJ)',
        'Rio Grande do Norte (RN)',
        'Rio Grande do Sul (RS)',
        'Rondônia (RO)',
        'Roraima (RR)',
        'Santa Catarina (SC)',
        'São Paulo (SP)',
        'Sergipe (SE)',
        'Tocantins (TO)',*/
    ],
    Mongolia : [
        'Arkhangai',
        'Arhangay',
        'Bayan-Olgii',
        'Bayan-Olgiy',
        'Bayankhongor',
        'Bayanhongor',
        'Bulgan',
        'Darkhan-Uul',
        'Dornod',
        'Dornogovi',
        'Govi-Altai',
        'Govisümber',
        'Khentii',
        'Hentiy',
        'Khovd',
        'Khovsgol',
        'Umnugovi (Ömnögovi)',
        'Orkhon',
        'Ovorkhangai',
        'Selenge',
        'Sukhbaatar',
        'Tuv (Töv)',
        'Uvs',
        'Zavkhan',
        'Ulaanbaatar (Municipality)',
    ],
    USA : [
        'Alabama',
        'Alaska',
        'Arizona',
        'Arkansas',
        'California',
        'Colorado',
        'Connecticut',
        'Delaware',
        'Florida',
        'Georgia',
        'Hawaii',
        'Idaho',
        'Illinois',
        'Indiana',
        'Iowa',
        'Kansas',
        'Kentucky',
        'Louisiana',
        'Maine',
        'Maryland',
        'Massachusetts',
        'Michigan',
        'Minnesota',
        'Mississippi',
        'Missouri',
        'Montana',
        'Nebraska',
        'Nevada',
        'New Hampshire',
        'New Jersey',
        'New Mexico',
        'New York',
        'North Carolina',
        'North Dakota',
        'Ohio',
        'Oklahoma',
        'Oregon',
        'Pennsylvania',
        'Rhode Island',
        'South Carolina',
        'South Dakota',
        'Tennessee',
        'Texas',
        'Utah',
        'Vermont',
        'Virginia',
        'Washington',
        'West Virginia',
        'Wisconsin',
        'Wyoming'
    ]
    };
}
